blank_issues_enabled: true
contact_links:
  - name: docs.microsoft.com site feedback
    url: https://github.com/MicrosoftDocs/feedback/issues/new/choose
    about: Log general docs.microsoft.com site issues here.
  - name: .NET Core issues
    url: https://github.com/dotnet/runtime/issues
    about: Log .NET Core product issues here.
