blank_issues_enabled: false
contact_links:
  - name: .NET platform and other product feedback
    url: https://aka.ms/feedback/report?space=61
    about: Log product issues here
  - name: .NET Q&A forums
    url: https://learn.microsoft.com/answers/products/dotnet
    about: Find answers to your technical questions about .NET
  - name: .NET tech community forums
    url: https://techcommunity.microsoft.com/t5/net/ct-p/dotnet
    about: Discuss .NET with community members
