items:
- uid: System.Runtime.Serialization.DataContractSerializerSettings
  id: DataContractSerializerSettings
  parent: System.Runtime.Serialization
  children:
  - System.Runtime.Serialization.DataContractSerializerSettings.DataContractResolver
  - System.Runtime.Serialization.DataContractSerializerSettings.KnownTypes
  - System.Runtime.Serialization.DataContractSerializerSettings.MaxItemsInObjectGraph
  - System.Runtime.Serialization.DataContractSerializerSettings.PreserveObjectReferences
  - System.Runtime.Serialization.DataContractSerializerSettings.RootName
  - System.Runtime.Serialization.DataContractSerializerSettings.RootNamespace
  - System.Runtime.Serialization.DataContractSerializerSettings.SerializeReadOnlyTypes
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: DataContractSerializerSettings
  fullName: System.Runtime.Serialization.DataContractSerializerSettings
  type: Class
  source:
    remote: &o0
      path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
      branch: master
      repo: https://github.com/chenkennt/corefx.git
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 14
  assemblies:
  - System.Private.DataContractSerialization
  namespace: System.Runtime.Serialization
  summary: Specifies data contract serializer settings.
  syntax:
    content: public class DataContractSerializerSettings
    content.vb: Public Class DataContractSerializerSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: System.Runtime.Serialization.DataContractSerializerSettings.RootName
  id: RootName
  parent: System.Runtime.Serialization.DataContractSerializerSettings
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: RootName
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.RootName
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 21
  assemblies:
  - System.Private.DataContractSerialization
  namespace: System.Runtime.Serialization
  summary: Gets or sets the root name of the selected object.
  syntax:
    content: public XmlDictionaryString RootName { get; set; }
    content.vb: Public Property RootName As XmlDictionaryString
    parameters: []
    return:
      type: System.Xml.XmlDictionaryString
- uid: System.Runtime.Serialization.DataContractSerializerSettings.RootNamespace
  id: RootNamespace
  parent: System.Runtime.Serialization.DataContractSerializerSettings
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: RootNamespace
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.RootNamespace
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 26
  assemblies:
  - System.Private.DataContractSerialization
  namespace: System.Runtime.Serialization
  summary: Gets or sets the root namespace for the specified object.
  syntax:
    content: public XmlDictionaryString RootNamespace { get; set; }
    content.vb: Public Property RootNamespace As XmlDictionaryString
    parameters: []
    return:
      type: System.Xml.XmlDictionaryString
- uid: System.Runtime.Serialization.DataContractSerializerSettings.KnownTypes
  id: KnownTypes
  parent: System.Runtime.Serialization.DataContractSerializerSettings
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: KnownTypes
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.KnownTypes
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 31
  assemblies:
  - System.Private.DataContractSerialization
  namespace: System.Runtime.Serialization
  summary: Gets or sets a collection of types that may be present in the object graph serialized using this instance of the DataContractSerializerSettings.
  syntax:
    content: public IEnumerable<Type> KnownTypes { get; set; }
    content.vb: Public Property KnownTypes As IEnumerable(Of Type)
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable{System.Type}
- uid: System.Runtime.Serialization.DataContractSerializerSettings.MaxItemsInObjectGraph
  id: MaxItemsInObjectGraph
  parent: System.Runtime.Serialization.DataContractSerializerSettings
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: MaxItemsInObjectGraph
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.MaxItemsInObjectGraph
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 36
  assemblies:
  - System.Private.DataContractSerialization
  namespace: System.Runtime.Serialization
  summary: Gets or sets the maximum number of items in an object graph to serialize or deserialize.
  syntax:
    content: public int MaxItemsInObjectGraph { get; set; }
    content.vb: Public Property MaxItemsInObjectGraph As Integer
    parameters: []
    return:
      type: System.Int32
- uid: System.Runtime.Serialization.DataContractSerializerSettings.PreserveObjectReferences
  id: PreserveObjectReferences
  parent: System.Runtime.Serialization.DataContractSerializerSettings
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: PreserveObjectReferences
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.PreserveObjectReferences
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 46
  assemblies:
  - System.Private.DataContractSerialization
  namespace: System.Runtime.Serialization
  summary: Gets or sets a value that specifies whether to use non-standard XML constructs to preserve object reference data.
  syntax:
    content: public bool PreserveObjectReferences { get; set; }
    content.vb: Public Property PreserveObjectReferences As Boolean
    parameters: []
    return:
      type: System.Boolean
- uid: System.Runtime.Serialization.DataContractSerializerSettings.DataContractResolver
  id: DataContractResolver
  parent: System.Runtime.Serialization.DataContractSerializerSettings
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: DataContractResolver
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.DataContractResolver
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 52
  assemblies:
  - System.Private.DataContractSerialization
  namespace: System.Runtime.Serialization
  summary: Gets or sets the component used to dynamically map xsi:type declarations to known contract types.
  syntax:
    content: public DataContractResolver DataContractResolver { get; set; }
    content.vb: Public Property DataContractResolver As DataContractResolver
    parameters: []
    return:
      type: System.Runtime.Serialization.DataContractResolver
- uid: System.Runtime.Serialization.DataContractSerializerSettings.SerializeReadOnlyTypes
  id: SerializeReadOnlyTypes
  parent: System.Runtime.Serialization.DataContractSerializerSettings
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: SerializeReadOnlyTypes
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.SerializeReadOnlyTypes
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 57
  assemblies:
  - System.Private.DataContractSerialization
  namespace: System.Runtime.Serialization
  summary: Gets or sets a value that specifies whether to serialize read only types.
  syntax:
    content: public bool SerializeReadOnlyTypes { get; set; }
    content.vb: Public Property SerializeReadOnlyTypes As Boolean
    parameters: []
    return:
      type: System.Boolean
references:
- uid: System.Runtime.Serialization
  isExternal: false
  name: System.Runtime.Serialization
  fullName: System.Runtime.Serialization
  type: Namespace
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Xml.XmlDictionaryString
  parent: System.Xml
  isExternal: false
  href: System.Xml.XmlDictionaryString.yml
  name: XmlDictionaryString
  fullName: System.Xml.XmlDictionaryString
  type: Class
- uid: System.Xml
  isExternal: false
  name: System.Xml
  fullName: System.Xml
  type: Namespace
- uid: System.Collections.Generic.IEnumerable{System.Type}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: System.Collections.Generic.IEnumerable`1.yml
  name: IEnumerable<Type>
  name.vb: IEnumerable(Of Type)
  fullName: System.Collections.Generic.IEnumerable<System.Type>
  fullName.vb: System.Collections.Generic.IEnumerable(Of System.Type)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    href: System.Collections.Generic.IEnumerable`1.yml
  - name: <
    fullName: <
  - uid: System.Type
    name: Type
    fullName: System.Type
    href: System.Type.yml
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    href: System.Collections.Generic.IEnumerable`1.yml
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Type
    name: Type
    fullName: System.Type
    href: System.Type.yml
  - name: )
    fullName: )
- uid: System.Collections.Generic.IEnumerable`1
  parent: System.Collections.Generic
  isExternal: true
  name: IEnumerable<T>
  name.vb: IEnumerable(Of T)
  fullName: System.Collections.Generic.IEnumerable<T>
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  fullName: System.Int32
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  fullName: System.Boolean
- uid: System.Runtime.Serialization.DataContractResolver
  parent: System.Runtime.Serialization
  isExternal: false
  href: System.Runtime.Serialization.DataContractResolver.yml
  name: DataContractResolver
  fullName: System.Runtime.Serialization.DataContractResolver
  type: Class
