items:
- uid: System.Security.Policy.ApplicationTrust
  id: ApplicationTrust
  parent: System.Security.Policy
  children:
  - System.Security.Policy.ApplicationTrust.#ctor
  - System.Security.Policy.ApplicationTrust.#ctor(System.Security.PermissionSet,System.Collections.Generic.IEnumerable{System.Security.Policy.StrongName})
  - System.Security.Policy.ApplicationTrust.Clone
  - System.Security.Policy.ApplicationTrust.DefaultGrantSet
  - System.Security.Policy.ApplicationTrust.FullTrustAssemblies
  href: System.Security.Policy.ApplicationTrust.yml
  name: ApplicationTrust
  fullName: System.Security.Policy.ApplicationTrust
  type: Class
  source:
    remote: &o0
      path: src/mscorlib/src/System/Security/Policy/ApplicationTrust.cs
      branch: master
      repo: https://github.com/chenkennt/coreclr.git
    path: src/mscorlib/src/System/Security/Policy/ApplicationTrust.cs
    startLine: 37
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: Encapsulates security decisions about an application. This class cannot be inherited.
  syntax:
    content: 'public sealed class ApplicationTrust : EvidenceBase, ISecurityEncodable'
    content.vb: Public NotInheritable Class ApplicationTrust Inherits EvidenceBase Implements ISecurityEncodable
  inheritance:
  - System.Object
  - System.Security.Policy.EvidenceBase
  implements:
  - System.Security.ISecurityEncodable
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: System.Security.Policy.ApplicationTrust.#ctor
  id: '#ctor'
  parent: System.Security.Policy.ApplicationTrust
  href: System.Security.Policy.ApplicationTrust.yml
  name: ApplicationTrust()
  fullName: System.Security.Policy.ApplicationTrust.ApplicationTrust()
  type: Constructor
  source:
    remote: *o0
    path: src/mscorlib/src/System/Security/Policy/ApplicationTrust.cs
    startLine: 71
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: Initializes a new instance of the @'System.Security.Policy.ApplicationTrust' class.
  syntax:
    content: public ApplicationTrust()
    content.vb: Public Sub New
- uid: System.Security.Policy.ApplicationTrust.#ctor(System.Security.PermissionSet,System.Collections.Generic.IEnumerable{System.Security.Policy.StrongName})
  id: '#ctor(System.Security.PermissionSet,System.Collections.Generic.IEnumerable{System.Security.Policy.StrongName})'
  parent: System.Security.Policy.ApplicationTrust
  href: System.Security.Policy.ApplicationTrust.yml
  name: ApplicationTrust(PermissionSet, IEnumerable<StrongName>)
  name.vb: ApplicationTrust(PermissionSet, IEnumerable(Of StrongName))
  fullName: System.Security.Policy.ApplicationTrust.ApplicationTrust(System.Security.PermissionSet, System.Collections.Generic.IEnumerable<System.Security.Policy.StrongName>)
  fullName.vb: System.Security.Policy.ApplicationTrust.ApplicationTrust(System.Security.PermissionSet, System.Collections.Generic.IEnumerable(Of System.Security.Policy.StrongName))
  type: Constructor
  source:
    remote: *o0
    path: src/mscorlib/src/System/Security/Policy/ApplicationTrust.cs
    startLine: 82
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: Initializes a new instance of the @'System.Security.Policy.ApplicationTrust' class using the provided grant set and collection of full-trust assemblies.
  syntax:
    content: public ApplicationTrust(PermissionSet defaultGrantSet, IEnumerable<StrongName> fullTrustAssemblies)
    content.vb: Public Sub New(defaultGrantSet As PermissionSet, fullTrustAssemblies As IEnumerable(Of StrongName))
    parameters:
    - id: defaultGrantSet
      type: System.Security.PermissionSet
      description: A default permission set that is granted to all assemblies that do not have specific grants.
    - id: fullTrustAssemblies
      type: System.Collections.Generic.IEnumerable{System.Security.Policy.StrongName}
      description: An array of strong names that represent assemblies that should be considered fully trusted in an application domain.
  exceptions:
  - type: System.ArgumentNullException
    description: '*defaultGrantSet* is null.'
  - type: System.ArgumentNullException
    description: '*fullTrustAssemblies* is null.'
  - type: System.ArgumentException
    description: '*fullTrustAssemblies* contains an assembly that does not have a @''System.Security.Policy.StrongName''.'
- uid: System.Security.Policy.ApplicationTrust.DefaultGrantSet
  id: DefaultGrantSet
  parent: System.Security.Policy.ApplicationTrust
  href: System.Security.Policy.ApplicationTrust.yml
  name: DefaultGrantSet
  fullName: System.Security.Policy.ApplicationTrust.DefaultGrantSet
  type: Property
  source:
    remote: *o0
    path: src/mscorlib/src/System/Security/Policy/ApplicationTrust.cs
    startLine: 127
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: Gets or sets the policy statement defining the default grant set.
  syntax:
    content: public PolicyStatement DefaultGrantSet { get; set; }
    content.vb: Public Property DefaultGrantSet As PolicyStatement
    parameters: []
    return:
      type: System.Security.Policy.PolicyStatement
- uid: System.Security.Policy.ApplicationTrust.FullTrustAssemblies
  id: FullTrustAssemblies
  parent: System.Security.Policy.ApplicationTrust
  href: System.Security.Policy.ApplicationTrust.yml
  name: FullTrustAssemblies
  fullName: System.Security.Policy.ApplicationTrust.FullTrustAssemblies
  type: Property
  source:
    remote: *o0
    path: src/mscorlib/src/System/Security/Policy/ApplicationTrust.cs
    startLine: 145
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: Gets the list of full-trust assemblies for this application trust.
  syntax:
    content: public IList<StrongName> FullTrustAssemblies { get; }
    content.vb: Public ReadOnly Property FullTrustAssemblies As IList(Of StrongName)
    parameters: []
    return:
      type: System.Collections.Generic.IList{System.Security.Policy.StrongName}
- uid: System.Security.Policy.ApplicationTrust.Clone
  id: Clone
  parent: System.Security.Policy.ApplicationTrust
  href: System.Security.Policy.ApplicationTrust.yml
  name: Clone()
  fullName: System.Security.Policy.ApplicationTrust.Clone()
  type: Method
  source:
    remote: *o0
    path: src/mscorlib/src/System/Security/Policy/ApplicationTrust.cs
    startLine: 322
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: Creates a new object that is a complete copy of the current instance.
  syntax:
    content: public override EvidenceBase Clone()
    content.vb: Public Overrides Function Clone As EvidenceBase
    return:
      type: System.Security.Policy.EvidenceBase
  overridden: System.Security.Policy.EvidenceBase.Clone
references:
- uid: System.Security.Policy
  isExternal: false
  name: System.Security.Policy
  fullName: System.Security.Policy
  type: Namespace
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Security.Policy.EvidenceBase
  parent: System.Security.Policy
  isExternal: false
  href: System.Security.Policy.EvidenceBase.yml
  name: EvidenceBase
  fullName: System.Security.Policy.EvidenceBase
  type: Class
  summary: Base class from which all objects to be used as Evidence must derive
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Security.PermissionSet
  parent: System.Security
  isExternal: false
  href: System.Security.PermissionSet.yml
  name: PermissionSet
  fullName: System.Security.PermissionSet
  type: Class
- uid: System.Collections.Generic.IEnumerable{System.Security.Policy.StrongName}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: System.Collections.Generic.IEnumerable`1.yml
  name: IEnumerable<StrongName>
  name.vb: IEnumerable(Of StrongName)
  fullName: System.Collections.Generic.IEnumerable<System.Security.Policy.StrongName>
  fullName.vb: System.Collections.Generic.IEnumerable(Of System.Security.Policy.StrongName)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    href: System.Collections.Generic.IEnumerable`1.yml
  - name: <
    fullName: <
  - uid: System.Security.Policy.StrongName
    name: StrongName
    fullName: System.Security.Policy.StrongName
    href: System.Security.Policy.StrongName.yml
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    href: System.Collections.Generic.IEnumerable`1.yml
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Security.Policy.StrongName
    name: StrongName
    fullName: System.Security.Policy.StrongName
    href: System.Security.Policy.StrongName.yml
  - name: )
    fullName: )
- uid: System.Security
  isExternal: false
  name: System.Security
  fullName: System.Security
  type: Namespace
- uid: System.Collections.Generic.IEnumerable`1
  parent: System.Collections.Generic
  isExternal: true
  name: IEnumerable<T>
  name.vb: IEnumerable(Of T)
  fullName: System.Collections.Generic.IEnumerable<T>
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.Security.Policy.PolicyStatement
  parent: System.Security.Policy
  isExternal: false
  href: System.Security.Policy.PolicyStatement.yml
  name: PolicyStatement
  fullName: System.Security.Policy.PolicyStatement
  type: Class
- uid: System.Collections.Generic.IList{System.Security.Policy.StrongName}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  href: System.Collections.Generic.IList`1.yml
  name: IList<StrongName>
  name.vb: IList(Of StrongName)
  fullName: System.Collections.Generic.IList<System.Security.Policy.StrongName>
  fullName.vb: System.Collections.Generic.IList(Of System.Security.Policy.StrongName)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    href: System.Collections.Generic.IList`1.yml
  - name: <
    fullName: <
  - uid: System.Security.Policy.StrongName
    name: StrongName
    fullName: System.Security.Policy.StrongName
    href: System.Security.Policy.StrongName.yml
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    href: System.Collections.Generic.IList`1.yml
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Security.Policy.StrongName
    name: StrongName
    fullName: System.Security.Policy.StrongName
    href: System.Security.Policy.StrongName.yml
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  name.vb: IList(Of T)
  fullName: System.Collections.Generic.IList<T>
  fullName.vb: System.Collections.Generic.IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Security.Policy.EvidenceBase.Clone
  parent: System.Security.Policy.EvidenceBase
  isExternal: false
  href: System.Security.Policy.EvidenceBase.yml
  name: Clone()
  fullName: System.Security.Policy.EvidenceBase.Clone()
  spec.csharp:
  - uid: System.Security.Policy.EvidenceBase.Clone
    name: Clone
    fullName: System.Security.Policy.EvidenceBase.Clone
    href: System.Security.Policy.EvidenceBase.yml
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Security.Policy.EvidenceBase.Clone
    name: Clone
    fullName: System.Security.Policy.EvidenceBase.Clone
    href: System.Security.Policy.EvidenceBase.yml
  - name: (
    fullName: (
  - name: )
    fullName: )
