items:
- uid: System.Environment.SpecialFolder
  id: Environment.SpecialFolder
  parent: System
  children:
  - System.Environment.SpecialFolder.ApplicationData
  - System.Environment.SpecialFolder.CommonApplicationData
  - System.Environment.SpecialFolder.CommonProgramFiles
  - System.Environment.SpecialFolder.Cookies
  - System.Environment.SpecialFolder.Desktop
  - System.Environment.SpecialFolder.DesktopDirectory
  - System.Environment.SpecialFolder.Favorites
  - System.Environment.SpecialFolder.History
  - System.Environment.SpecialFolder.InternetCache
  - System.Environment.SpecialFolder.LocalApplicationData
  - System.Environment.SpecialFolder.MyComputer
  - System.Environment.SpecialFolder.MyDocuments
  - System.Environment.SpecialFolder.MyMusic
  - System.Environment.SpecialFolder.MyPictures
  - System.Environment.SpecialFolder.MyVideos
  - System.Environment.SpecialFolder.Personal
  - System.Environment.SpecialFolder.ProgramFiles
  - System.Environment.SpecialFolder.Programs
  - System.Environment.SpecialFolder.Recent
  - System.Environment.SpecialFolder.SendTo
  - System.Environment.SpecialFolder.StartMenu
  - System.Environment.SpecialFolder.Startup
  - System.Environment.SpecialFolder.System
  - System.Environment.SpecialFolder.Templates
  href: System.Environment.SpecialFolder.yml
  name: Environment.SpecialFolder
  fullName: System.Environment.SpecialFolder
  type: Enum
  source:
    remote: &o0
      path: src/mscorlib/src/System/Environment.cs
      branch: master
      repo: https://github.com/chenkennt/coreclr.git
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1555
  assemblies:
  - mscorlib
  namespace: System
  summary: Specifies enumerated constants used to retrieve directory paths to system special folders.
  syntax:
    content: public enum SpecialFolder
    content.vb: Public Enum SpecialFolder
- uid: System.Environment.SpecialFolder.ApplicationData
  id: ApplicationData
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: ApplicationData
  fullName: System.Environment.SpecialFolder.ApplicationData
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1564
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory that serves as a common repository for application-specific data for the current roaming user.
  syntax:
    content: ApplicationData = 26
- uid: System.Environment.SpecialFolder.CommonApplicationData
  id: CommonApplicationData
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: CommonApplicationData
  fullName: System.Environment.SpecialFolder.CommonApplicationData
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1569
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory that serves as a common repository for application-specific data that is used by all users.
  syntax:
    content: CommonApplicationData = 35
- uid: System.Environment.SpecialFolder.LocalApplicationData
  id: LocalApplicationData
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: LocalApplicationData
  fullName: System.Environment.SpecialFolder.LocalApplicationData
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1574
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory that serves as a common repository for application-specific data that is used by the current, non-roaming user.
  syntax:
    content: LocalApplicationData = 28
- uid: System.Environment.SpecialFolder.Cookies
  id: Cookies
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: Cookies
  fullName: System.Environment.SpecialFolder.Cookies
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1579
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory that serves as a common repository for Internet cookies.
  syntax:
    content: Cookies = 33
- uid: System.Environment.SpecialFolder.Desktop
  id: Desktop
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: Desktop
  fullName: System.Environment.SpecialFolder.Desktop
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1580
  assemblies:
  - mscorlib
  namespace: System
  summary: The logical Desktop rather than the physical file system location.
  syntax:
    content: Desktop = 0
- uid: System.Environment.SpecialFolder.Favorites
  id: Favorites
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: Favorites
  fullName: System.Environment.SpecialFolder.Favorites
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1585
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory that serves as a common repository for the user's favorite items.
  syntax:
    content: Favorites = 6
- uid: System.Environment.SpecialFolder.History
  id: History
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: History
  fullName: System.Environment.SpecialFolder.History
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1590
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory that serves as a common repository for Internet history items.
  syntax:
    content: History = 34
- uid: System.Environment.SpecialFolder.InternetCache
  id: InternetCache
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: InternetCache
  fullName: System.Environment.SpecialFolder.InternetCache
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1595
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory that serves as a common repository for temporary Internet files.
  syntax:
    content: InternetCache = 32
- uid: System.Environment.SpecialFolder.Programs
  id: Programs
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: Programs
  fullName: System.Environment.SpecialFolder.Programs
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1600
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory that contains the user's program groups.
  syntax:
    content: Programs = 2
- uid: System.Environment.SpecialFolder.MyComputer
  id: MyComputer
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: MyComputer
  fullName: System.Environment.SpecialFolder.MyComputer
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1601
  assemblies:
  - mscorlib
  namespace: System
  summary: The My Computer folder.
  syntax:
    content: MyComputer = 17
- uid: System.Environment.SpecialFolder.MyMusic
  id: MyMusic
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: MyMusic
  fullName: System.Environment.SpecialFolder.MyMusic
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1602
  assemblies:
  - mscorlib
  namespace: System
  summary: The My Music folder.
  syntax:
    content: MyMusic = 13
- uid: System.Environment.SpecialFolder.MyPictures
  id: MyPictures
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: MyPictures
  fullName: System.Environment.SpecialFolder.MyPictures
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1603
  assemblies:
  - mscorlib
  namespace: System
  summary: The My Pictures folder.
  syntax:
    content: MyPictures = 39
- uid: System.Environment.SpecialFolder.MyVideos
  id: MyVideos
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: MyVideos
  fullName: System.Environment.SpecialFolder.MyVideos
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1605
  assemblies:
  - mscorlib
  namespace: System
  summary: "The file system directory that serves as a repository for videos that belong to a user.  Added in the .NET FrameworkÂ 4."
  syntax:
    content: MyVideos = 14
- uid: System.Environment.SpecialFolder.Recent
  id: Recent
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: Recent
  fullName: System.Environment.SpecialFolder.Recent
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1610
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory that contains the user's most recently used documents.
  syntax:
    content: Recent = 8
- uid: System.Environment.SpecialFolder.SendTo
  id: SendTo
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: SendTo
  fullName: System.Environment.SpecialFolder.SendTo
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1614
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory that contains the Send To menu items.
  syntax:
    content: SendTo = 9
- uid: System.Environment.SpecialFolder.StartMenu
  id: StartMenu
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: StartMenu
  fullName: System.Environment.SpecialFolder.StartMenu
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1618
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory that contains the Start menu items.
  syntax:
    content: StartMenu = 11
- uid: System.Environment.SpecialFolder.Startup
  id: Startup
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: Startup
  fullName: System.Environment.SpecialFolder.Startup
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1624
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory that corresponds to the user's Startup program group.
  syntax:
    content: Startup = 7
- uid: System.Environment.SpecialFolder.System
  id: System
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: System
  fullName: System.Environment.SpecialFolder.System
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1628
  assemblies:
  - mscorlib
  namespace: System
  summary: The System directory.
  syntax:
    content: System = 37
- uid: System.Environment.SpecialFolder.Templates
  id: Templates
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: Templates
  fullName: System.Environment.SpecialFolder.Templates
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1633
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory that serves as a common repository for document templates.
  syntax:
    content: Templates = 21
- uid: System.Environment.SpecialFolder.DesktopDirectory
  id: DesktopDirectory
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: DesktopDirectory
  fullName: System.Environment.SpecialFolder.DesktopDirectory
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1639
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory used to physically store file objects on the desktop.
  syntax:
    content: DesktopDirectory = 16
- uid: System.Environment.SpecialFolder.Personal
  id: Personal
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: Personal
  fullName: System.Environment.SpecialFolder.Personal
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1643
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory that serves as a common repository for documents.
  syntax:
    content: Personal = 5
- uid: System.Environment.SpecialFolder.MyDocuments
  id: MyDocuments
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: MyDocuments
  fullName: System.Environment.SpecialFolder.MyDocuments
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1647
  assemblies:
  - mscorlib
  namespace: System
  summary: The My Documents folder.
  syntax:
    content: MyDocuments = 5
- uid: System.Environment.SpecialFolder.ProgramFiles
  id: ProgramFiles
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: ProgramFiles
  fullName: System.Environment.SpecialFolder.ProgramFiles
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1651
  assemblies:
  - mscorlib
  namespace: System
  summary: The program files directory.On a non-x86 system, passing @'System.Environment.SpecialFolder.ProgramFiles' to the @'System.Environment.GetFolderPath(System.Environment.SpecialFolder)' method returns the path for non-x86 programs. To get the x86 program files directory on a non-x86 system, use the @'System.Environment.SpecialFolder.ProgramFilesX86' member.
  syntax:
    content: ProgramFiles = 38
- uid: System.Environment.SpecialFolder.CommonProgramFiles
  id: CommonProgramFiles
  parent: System.Environment.SpecialFolder
  href: System.Environment.SpecialFolder.yml
  name: CommonProgramFiles
  fullName: System.Environment.SpecialFolder.CommonProgramFiles
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1655
  assemblies:
  - mscorlib
  namespace: System
  summary: The directory for components that are shared across applications.To get the x86 common program files directory on a non-x86 system, use the @'System.Environment.SpecialFolder.ProgramFilesX86' member.
  syntax:
    content: CommonProgramFiles = 43
references:
- uid: System
  isExternal: false
  name: System
  fullName: System
  type: Namespace
