items:
- uid: System.EnvironmentVariableTarget
  id: EnvironmentVariableTarget
  parent: System
  children:
  - System.EnvironmentVariableTarget.Machine
  - System.EnvironmentVariableTarget.Process
  - System.EnvironmentVariableTarget.User
  href: System.EnvironmentVariableTarget.yml
  name: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
  type: Enum
  source:
    remote: &o0
      path: src/mscorlib/src/System/Environment.cs
      branch: master
      repo: https://github.com/chenkennt/coreclr.git
    path: src/mscorlib/src/System/Environment.cs
    startLine: 31
  assemblies:
  - mscorlib
  namespace: System
  summary: Specifies the location where an environment variable is stored or retrieved in a set or get operation.
  syntax:
    content: public enum EnvironmentVariableTarget
    content.vb: Public Enum EnvironmentVariableTarget
- uid: System.EnvironmentVariableTarget.Process
  id: Process
  parent: System.EnvironmentVariableTarget
  href: System.EnvironmentVariableTarget.yml
  name: Process
  fullName: System.EnvironmentVariableTarget.Process
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 33
  assemblies:
  - mscorlib
  namespace: System
  summary: The environment variable is stored or retrieved from the environment block associated with the current process.
  syntax:
    content: Process = 0
- uid: System.EnvironmentVariableTarget.User
  id: User
  parent: System.EnvironmentVariableTarget
  href: System.EnvironmentVariableTarget.yml
  name: User
  fullName: System.EnvironmentVariableTarget.User
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 35
  assemblies:
  - mscorlib
  namespace: System
  summary: The environment variable is stored or retrieved from the HKEY_CURRENT_USER\Environment key in the Windows operating system registry.
  syntax:
    content: User = 1
- uid: System.EnvironmentVariableTarget.Machine
  id: Machine
  parent: System.EnvironmentVariableTarget
  href: System.EnvironmentVariableTarget.yml
  name: Machine
  fullName: System.EnvironmentVariableTarget.Machine
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 36
  assemblies:
  - mscorlib
  namespace: System
  summary: The environment variable is stored or retrieved from the HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment key in the Windows operating system registry.
  syntax:
    content: Machine = 2
references:
- uid: System
  isExternal: false
  name: System
  fullName: System
  type: Namespace
