items:
- uid: System.Security
  id: System.Security
  children:
  - System.Security.AllowPartiallyTrustedCallersAttribute
  - System.Security.CodeAccessPermission
  - System.Security.HostProtectionException
  - System.Security.HostSecurityManager
  - System.Security.HostSecurityManagerOptions
  - System.Security.IEvidenceFactory
  - System.Security.IPermission
  - System.Security.ISecurityEncodable
  - System.Security.ISecurityPolicyEncodable
  - System.Security.IStackWalk
  - System.Security.NamedPermissionSet
  - System.Security.PartialTrustVisibilityLevel
  - System.Security.PermissionSet
  - System.Security.PolicyLevelType
  - System.Security.SecureString
  - System.Security.SecureStringMarshal
  - System.Security.SecurityContextSource
  - System.Security.SecurityCriticalAttribute
  - System.Security.SecurityElement
  - System.Security.SecurityException
  - System.Security.SecurityManager
  - System.Security.SecuritySafeCriticalAttribute
  - System.Security.SecurityState
  - System.Security.SecurityTransparentAttribute
  - System.Security.SecurityTreatAsSafeAttribute
  - System.Security.SecurityZone
  - System.Security.SuppressUnmanagedCodeSecurityAttribute
  - System.Security.UnverifiableCodeAttribute
  - System.Security.VerificationException
  - System.Security.XmlSyntaxException
  href: System.Security.yml
  name: System.Security
  fullName: System.Security
  type: Namespace
  source:
    remote:
      path: src/System.Security.SecureString/src/System/Security/SafeBSTRHandle.cs
      branch: master
      repo: https://github.com/chenkennt/corefx.git
    path: src/System.Security.SecureString/src/System/Security/SafeBSTRHandle.cs
    startLine: 6
  assemblies:
  - System.Security.SecureString
  summary: The @'System.Security' namespace provides the underlying structure of the common language runtime security system, including base classes for permissions.
references:
- uid: System.Security.SecureString
  parent: System.Security
  isExternal: false
  href: System.Security.SecureString.yml
  name: SecureString
  fullName: System.Security.SecureString
  type: Class
- uid: System.Security.SecureStringMarshal
  isExternal: false
  href: System.Security.SecureStringMarshal.yml
  name: SecureStringMarshal
  fullName: System.Security.SecureStringMarshal
  type: Class
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  href: System.Security.SecurityElement.yml
  name: SecurityElement
  fullName: System.Security.SecurityElement
  type: Class
- uid: System.Security.XmlSyntaxException
  isExternal: false
  href: System.Security.XmlSyntaxException.yml
  name: XmlSyntaxException
  fullName: System.Security.XmlSyntaxException
  type: Class
- uid: System.Security.SuppressUnmanagedCodeSecurityAttribute
  isExternal: false
  href: System.Security.SuppressUnmanagedCodeSecurityAttribute.yml
  name: SuppressUnmanagedCodeSecurityAttribute
  fullName: System.Security.SuppressUnmanagedCodeSecurityAttribute
  type: Class
- uid: System.Security.UnverifiableCodeAttribute
  isExternal: false
  href: System.Security.UnverifiableCodeAttribute.yml
  name: UnverifiableCodeAttribute
  fullName: System.Security.UnverifiableCodeAttribute
  type: Class
- uid: System.Security.AllowPartiallyTrustedCallersAttribute
  isExternal: false
  href: System.Security.AllowPartiallyTrustedCallersAttribute.yml
  name: AllowPartiallyTrustedCallersAttribute
  fullName: System.Security.AllowPartiallyTrustedCallersAttribute
  type: Class
- uid: System.Security.PartialTrustVisibilityLevel
  parent: System.Security
  isExternal: false
  href: System.Security.PartialTrustVisibilityLevel.yml
  name: PartialTrustVisibilityLevel
  fullName: System.Security.PartialTrustVisibilityLevel
  type: Enum
- uid: System.Security.SecurityCriticalAttribute
  isExternal: false
  href: System.Security.SecurityCriticalAttribute.yml
  name: SecurityCriticalAttribute
  fullName: System.Security.SecurityCriticalAttribute
  type: Class
- uid: System.Security.SecurityTreatAsSafeAttribute
  isExternal: false
  href: System.Security.SecurityTreatAsSafeAttribute.yml
  name: SecurityTreatAsSafeAttribute
  fullName: System.Security.SecurityTreatAsSafeAttribute
  type: Class
- uid: System.Security.SecuritySafeCriticalAttribute
  isExternal: false
  href: System.Security.SecuritySafeCriticalAttribute.yml
  name: SecuritySafeCriticalAttribute
  fullName: System.Security.SecuritySafeCriticalAttribute
  type: Class
- uid: System.Security.SecurityTransparentAttribute
  isExternal: false
  href: System.Security.SecurityTransparentAttribute.yml
  name: SecurityTransparentAttribute
  fullName: System.Security.SecurityTransparentAttribute
  type: Class
- uid: System.Security.CodeAccessPermission
  parent: System.Security
  isExternal: false
  href: System.Security.CodeAccessPermission.yml
  name: CodeAccessPermission
  fullName: System.Security.CodeAccessPermission
  type: Class
- uid: System.Security.IEvidenceFactory
  parent: System.Security
  isExternal: false
  href: System.Security.IEvidenceFactory.yml
  name: IEvidenceFactory
  fullName: System.Security.IEvidenceFactory
  type: Interface
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  href: System.Security.IPermission.yml
  name: IPermission
  fullName: System.Security.IPermission
  type: Interface
- uid: System.Security.ISecurityEncodable
  parent: System.Security
  isExternal: false
  href: System.Security.ISecurityEncodable.yml
  name: ISecurityEncodable
  fullName: System.Security.ISecurityEncodable
  type: Interface
- uid: System.Security.ISecurityPolicyEncodable
  parent: System.Security
  isExternal: false
  href: System.Security.ISecurityPolicyEncodable.yml
  name: ISecurityPolicyEncodable
  fullName: System.Security.ISecurityPolicyEncodable
  type: Interface
- uid: System.Security.IStackWalk
  parent: System.Security
  isExternal: false
  href: System.Security.IStackWalk.yml
  name: IStackWalk
  fullName: System.Security.IStackWalk
  type: Interface
- uid: System.Security.HostSecurityManagerOptions
  parent: System.Security
  isExternal: false
  href: System.Security.HostSecurityManagerOptions.yml
  name: HostSecurityManagerOptions
  fullName: System.Security.HostSecurityManagerOptions
  type: Enum
- uid: System.Security.HostSecurityManager
  isExternal: false
  href: System.Security.HostSecurityManager.yml
  name: HostSecurityManager
  fullName: System.Security.HostSecurityManager
  type: Class
- uid: System.Security.NamedPermissionSet
  isExternal: false
  href: System.Security.NamedPermissionSet.yml
  name: NamedPermissionSet
  fullName: System.Security.NamedPermissionSet
  type: Class
- uid: System.Security.PermissionSet
  parent: System.Security
  isExternal: false
  href: System.Security.PermissionSet.yml
  name: PermissionSet
  fullName: System.Security.PermissionSet
  type: Class
- uid: System.Security.SecurityContextSource
  parent: System.Security
  isExternal: false
  href: System.Security.SecurityContextSource.yml
  name: SecurityContextSource
  fullName: System.Security.SecurityContextSource
  type: Enum
- uid: System.Security.SecurityException
  isExternal: false
  href: System.Security.SecurityException.yml
  name: SecurityException
  fullName: System.Security.SecurityException
  type: Class
- uid: System.Security.SecurityState
  parent: System.Security
  isExternal: false
  href: System.Security.SecurityState.yml
  name: SecurityState
  fullName: System.Security.SecurityState
  type: Class
- uid: System.Security.HostProtectionException
  isExternal: false
  href: System.Security.HostProtectionException.yml
  name: HostProtectionException
  fullName: System.Security.HostProtectionException
  type: Class
- uid: System.Security.PolicyLevelType
  parent: System.Security
  isExternal: false
  href: System.Security.PolicyLevelType.yml
  name: PolicyLevelType
  fullName: System.Security.PolicyLevelType
  type: Enum
- uid: System.Security.SecurityManager
  isExternal: false
  href: System.Security.SecurityManager.yml
  name: SecurityManager
  fullName: System.Security.SecurityManager
  type: Class
- uid: System.Security.SecurityZone
  parent: System.Security
  isExternal: false
  href: System.Security.SecurityZone.yml
  name: SecurityZone
  fullName: System.Security.SecurityZone
  type: Enum
- uid: System.Security.VerificationException
  isExternal: false
  href: System.Security.VerificationException.yml
  name: VerificationException
  fullName: System.Security.VerificationException
  type: Class
- uid: System.Security
  isExternal: false
  name: System.Security
  fullName: System.Security
  type: Namespace
