name: "clean repo - snippets"

on:
  schedule:
    - cron: "0 1 1 * *" # Runs at 01:00, on day 1 of the month
  workflow_dispatch:

permissions:
  contents: read

jobs:
  clean-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Call clean repo
      - name: Clean repo
        id: clean-repo-step
        uses: dotnet/docs-tools/cleanrepo@main
        with:
          function: "FindOrphanedSnippets"
          docfx_directory: "."
          target_directory: "docs"
          url_base_path: "/dotnet"

      # Create the PR for the work done by the "clean repo" tool
      - name: create-pull-request
        uses: dotnet/actions-create-pull-request@v4
        with:
          branch: cleanrepo-orphaned-snippets
          title: "Monthly chores: Delete orphaned snippets"
          commit-message: "Bot ðŸ¤– generated CleanRepo tool run"
          body: "Find and delete orphaned snippets. Contributes to #..."
