name: "clean repo - relative links"

on:
  schedule:
    - cron: "0 1 1 * *" # Runs at 01:00, on day 1 of the month
  workflow_dispatch:

permissions:
  contents: read

jobs:
  clean-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Call clean repo
      - name: Clean repo
        id: clean-repo-step
        uses: dotnet/docs-tools/cleanrepo@main
        with:
          function: "ReplaceWithRelativeLinks"
          docfx_directory: "."
          target_directory: "docs"
          url_base_path: "/dotnet"

      # Create the PR for the work done by the "clean repo" tool
      - name: create-pull-request
        uses: dotnet/actions-create-pull-request@v4
        with:
          branch: cleanrepo-relative-links
          title: "Monthly chores: Use relative links"
          commit-message: "Bot ðŸ¤– generated CleanRepo tool run"
          body: "Find and replace absolute links with relative links. Contributes to #..."
