name: "clean repo - redirect hops"

on:
  schedule:
    - cron: "0 1 1 * *" # Runs at 01:00, on day 1 of the month
  workflow_dispatch:

permissions:
  contents: read

jobs:
  clean-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Call clean repo
      - name: Clean repo
        id: clean-repo-step
        uses: dotnet/docs-tools/cleanrepo@main
        with:
          function: "RemoveRedirectHops"
          docfx_directory: "."
          target_directory: "."
          url_base_path: "/dotnet"

      # Create the PR for the work done by the "clean repo" tool
      - name: create-pull-request
        uses: dotnet/actions-create-pull-request@v4
        with:
          branch: cleanrepo-remove-hops
          title: "Monthly chores: Remove redirect hops"
          commit-message: "Bot ðŸ¤– generated CleanRepo tool run"
          body: "Remove redirect hops, for example, if a -> b and b -> c, replace a -> b with a -> c. Contributes to #..."
