name: Markdownlint

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - ".markdownlint-cli2.jsonc"
      - ".github/workflows/markdownlint.yml"
      - ".github/workflows/markdownlint-problem-matcher.json"
  pull_request:
    paths:
      - "**/*.md"
      - ".markdownlint-cli2.jsonc"
      - ".github/workflows/markdownlint.yml"
      - ".github/workflows/markdownlint-problem-matcher.json"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      statuses: write

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js
        uses: actions/setup-node@c2ac33f2c62f978d6c944d9648125a294e56dc0b
        with:
          node-version: 20.x
      - name: Run Markdownlint
        run: |
          echo "::add-matcher::.github/workflows/markdownlint-problem-matcher.json"
          npm i -g markdownlint-cli2
          markdownlint-cli2 "**/*.md"
