name: Markdownlint

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - ".markdownlint-cli2.jsonc"
      - ".github/workflows/markdownlint.yml"
      - ".github/workflows/markdownlint-problem-matcher.json"
  pull_request:
    paths:
      - "**/*.md"
      - ".markdownlint-cli2.jsonc"
      - ".github/workflows/markdownlint.yml"
      - ".github/workflows/markdownlint-problem-matcher.json"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      statuses: write

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
        with:
          node-version: 16.x
      - name: Run Markdownlint
        run: |
          echo "::add-matcher::.github/workflows/markdownlint-problem-matcher.json"
          npm i -g markdownlint-cli2
          markdownlint-cli2 "**/*.md"
