name: "quest import"
on:
  issues:
    types:
      [ labeled ]
  workflow_dispatch:
    inputs:
      reason:
        description: "The reason for running the workflow"
        required: true
        default: "Manual run"
      issue:
        description: "The issue number to manually test"
        required: true

jobs:
  import:
    if: github.event.label.name == join(fromJson('[":", "world_map", ":", " reQUEST"]'), '') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: "Print manual run reason"
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Reason: ${{ github.event.inputs.reason }}"
          echo "Issue number: ${{ github.event.inputs.issue }}"

      - name: sequester
        id: sequester
        uses: BillWagner/Quest2GitHub@main
        env:
          ImportOptions__ApiKeys__GitHubToken: ${{ secrets.GITHUB_TOKEN }}
          ImportOptions__ApiKeys__OSPOKey: ${{ secrets.OSPO_KEY }}
          ImportOptions__ApiKeys__QuestKey: ${{ secrets.QUEST_KEY }}
        with:
          org: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          
