name: "target supported version"

on:
    # Triggers the workflow on push or pull request events but only for the default branch
    schedule:
        - cron: "0 0 1 * *"
    workflow_dispatch:
        inputs:
            reason:
                description: "The reason for running the workflow"
                required: true
                default: "Manual run"
            support:
                description: "The support level to target (STS, LTS, or Preview)."
                required: true
                default: "STS"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    version-sweep:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:

            # Start the .NET version updater action
            # A composite of the .NET Version Sweeper and the .NET Upgrade Assistant
            - name: .NET version updater
              id: dotnet-version-updater
              uses: dotnet/docs-tools/actions/dotnet-version-updater@main
              with:
                  support: ${{ github.event.inputs.support }}