name: "generate what's new article"

on:
  schedule:
    - cron: "0 2 1 * *" # The first of every month at 2 AM
  workflow_dispatch:
    inputs:
      reason:
        description: "The reason for running the workflow"
        required: true
        default: "Manual run"

jobs:
  create-what-is-new:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: "Print manual run reason"
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Reason: ${{ github.event.inputs.reason }}"

      - uses: dotnet/docs-tools/WhatsNew.Cli@main
        env:
          GitHubKey: ${{ secrets.GITHUB_TOKEN }}
          OspoKey: ${{ secrets.OSPO_KEY }}
        with:
          owner: dotnet
          repo: docs
          savedir: './docs/whats-new'

      - name: create-pull-request
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54
        with:
          branch: create-whatsnew-pull-request/patch
          title: "What's new article"
          commit-message: 'Bot ðŸ¤– generated "What''s new article"'
          body: "Automated creation of What's new article."
